#OneBot11 WebSocket地址
socket_url: "ws://127.0.0.1:3001"
access_token: ""

#需要互通的QQ群号
target_group_id: 123456

#消息格式
format:
  #游戏内显示格式
  qq_to_mc: "<gray>Q群: <white>[<aqua>%nickname%<white>]: "
  #QQ群显示格式
  mc_to_qq: "[%player%]: %message%"